server:
  port: 8000

# spring config
spring:
  application:
    name: simple-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    password: xxxx
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1

# mybatis config
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: top.cadecode
  configuration:
    map-underscore-to-camel-case: true

# log config
logging:
  file:
    path: c:/logs

# custom config
custom:
  jwt:
    header: token
    refresh-header: refresh-token
    expiration: 86400
    refresh-expiration: 86400
    secret: 12345678123456781234567812345678

# simple-rest-admin 配置
sra:
  config:
    dynamic-ds-on: true
  # 动态数据源配置
  dynamic-ds:
    master: db1
    datasource:
      db1:
        # url 加上 p6spy 开启 sql 监控
        jdbc-url: jdbc:p6spy:mysql://localhost:3306/demo?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        username: root
        password: xxxx
        pool-name: db1_pool
      db2:
        jdbc-url: jdbc:p6spy:mysql://localhost:3306/demo_cluster?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        username: root
        password: xxxx
        pool-name: db2_pool

